TourSite/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TourSite.Models;
using TourSite.Login;
namespace TourSite.Controllers
{
    /*
     NOT: [LoginFilter] kısıtlamasını sınıf tanımının (public class xxxController : Controller) başına yazarak, sınıftaki bütün metodlara kullanıcı girişi yapılarak ulaşılmasını sağlamış oluruz.
         */
    [LoginFilter]
    public class KullaniciController : Controller
    {


        Tablolar db = new Tablolar();
        public ActionResult Index()
        {
            return View(db.kullanici.ToList());
        }

        public ActionResult ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ekle(Kullanici kayit)
        {
            db.kullanici.Add(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult sil(int id = 0)
        {
            Kullanici kayit = db.kullanici.Find(id);
            db.kullanici.Remove(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult duzelt(int id = 0)
        {
            Kullanici kayit = db.kullanici.Find(id);
            return View(kayit);
        }


        [HttpPost]
        public ActionResult duzelt(Kullanici kayit)
        {
            db.Entry(kayit).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

TourSite/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TourSite.Models;
namespace TourSite.Controllers
{
    public class PartialController : Controller
    {
        Tablolar db = new Tablolar();
        public PartialViewResult ustmenu()
        {

            ViewBag.yeniyorumsayisi = db.turyorumlari.Where(kayit => kayit.onay == false).Count();

            ViewBag.yenirezsayisi = db.rezervasyon.Where(kayit => kayit.onay == false).Count();

            ViewBag.kullanici = Login.Login.aktifKul.adi + " " + Login.Login.aktifKul.soyadi;
            return PartialView("_ustmenu");
        }

    }
}

TourSite/Controllers/SayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TourSite.Models;
using System.IO;
namespace TourSite.Controllers
{
    public class SayfaController : Controller
    {


        Tablolar db = new Tablolar();
        public ActionResult Index()
        {
            return View(db.sayfa.ToList());
        }

        public ActionResult ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ekle(Sayfa kayit)
        {
            db.sayfa.Add(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult sil(int id = 0)
        {
            Sayfa kayit = db.sayfa.Find(id);
            db.sayfa.Remove(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult duzelt(int id = 0)
        {
            Sayfa kayit = db.sayfa.Find(id);
            return View(kayit);
        }


        [HttpPost]
        public ActionResult duzelt(Sayfa kayit)
        {
            db.Entry(kayit).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult resimler(int sayfaid = 0)
        {
            return View(db.sayfaresimleri.Where(kayit => kayit.sayfa_id == sayfaid).ToList());
        }

        public ActionResult resimekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult resimekle(HttpPostedFileBase resimadi, int sayfaid)
        {
            if (resimadi.ContentLength > 0)
            {
                string filePath = Path.Combine(Server.MapPath("~/Content/images"), Guid.NewGuid().ToString() + "_" + Path.GetFileName(resimadi.FileName));
                resimadi.SaveAs(filePath);
                SayfaResimleri sr = new SayfaResimleri();

                sr.sayfa_id = sayfaid;
                sr.resimadi = Path.GetFileName(filePath);
                db.sayfaresimleri.Add(sr);
                db.SaveChanges();
            }
            return View();
        }

        public ActionResult resimsil(int[] resim_id)
        {
            foreach (int resimID in resim_id)
            {
                //resimler SayfaResimleris tablosundan silinir 
                SayfaResimleri kayit = db.sayfaresimleri.Find(resimID);
                db.sayfaresimleri.Remove(kayit);

                //resimler images klasöründen silinir 
                string fullPath = Request.MapPath("~/Content/images/" + kayit.resimadi);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
            db.SaveChanges();
            return Json("Seçili resimler silindi!");
        }




    }
}

TourSite/Controllers/TurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TourSite.Models;
using System.IO;
namespace TourSite.Controllers
{
    public class TurController : Controller
    {


        Tablolar db = new Tablolar();
        public ActionResult Index()
        {
            return View(db.tur.ToList());
        }

        public ActionResult ekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ekle(Tur kayit)
        {
            db.tur.Add(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult sil(int id = 0)
        {
            Tur kayit = db.tur.Find(id);
            db.tur.Remove(kayit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult duzelt(int id = 0)
        {
            Tur kayit = db.tur.Find(id);
            return View(kayit);
        }


        [HttpPost]
        public ActionResult duzelt(Tur kayit)
        {
            db.Entry(kayit).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult resimler(int turid = 0)
        {
            return View(db.turresimleri.Where(kayit => kayit.tur_id == turid).ToList());
        }


        public ActionResult resimekle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult resimekle(HttpPostedFileBase resimadi, int turid)
        {
            if (resimadi.ContentLength > 0)
            {
                string filePath = Path.Combine(Server.MapPath("~/Content/images"), Guid.NewGuid().ToString() + "_" + Path.GetFileName(resimadi.FileName));
                resimadi.SaveAs(filePath);
                TurResimleri tr = new TurResimleri();

                tr.tur_id = turid;
                tr.resimadi = Path.GetFileName(filePath);
                db.turresimleri.Add(tr);
                db.SaveChanges();
            }
            return View();
        }


        public ActionResult resimsil(int[] resim_id)
        {
            foreach (int resimID in resim_id)
            {
                //resimler TurResimleris tablosundan silinir 
                TurResimleri kayit = db.turresimleri.Find(resimID);
                db.turresimleri.Remove(kayit);

                //resimler images klasöründen silinir 
                string fullPath = Request.MapPath("~/Content/images/" + kayit.resimadi);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
            db.SaveChanges();
            return Json("Seçili resimler silindi!");
        }

    }
}

TourSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
@{Html.RenderAction("ustmenu", "Partial");}

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

TourSite/Views/Shared/_ustmenu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li>@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                <li>@Html.ActionLink("Kullanıcılar", "Index", "Kullanici")</li>
                <li>@Html.ActionLink("Sayfalar", "Index", "Sayfa")</li>
                <li>@Html.ActionLink("Turlar", "Index", "Tur")</li>
                <li>
                    <a href="@Url.Action("Index", "TurYorumlari")">
                        Tur Yorumları
                        @if (ViewBag.yeniyorumsayisi > 0)
                        {
                            <span class="badge">@ViewBag.yeniyorumsayisi</span>
                        }
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "Rezervasyon")">
                        Rezervasyonlar
                        @if (ViewBag.yenirezsayisi > 0)
                        {
                            <span class="badge">@ViewBag.yenirezsayisi</span>
                        }
                    </a>
                </li>




                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ViewBag.kullanici<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Oturumu Kapat", "logout", "Home")</li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</div>